version: "3.7"
services:
  kong-redis-1:
    image: redis:latest
    container_name: kong-redis-1
    command: "redis-server --replica-read-only no"
    volumes:
      - ./db/redis_master:/data
    ports:
      - "6379:6379"
  kong-redis-2:
    image: redis:latest
    container_name: kong-redis-2
    command: "redis-server --replica-read-only no"
    ports:
      - "6380:6379"
    volumes:
      - ./db/redis_replicas:/data
  kong-psql:
    image: postgres:9.6
    volumes:
      - ./db/psql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kongpass
    ports:
      - "5432:5432"
  kong-gateway-db-bootstrap:
    image: kong/kong-gateway:3.1.1.3-alpine
    restart: on-failure
    depends_on:
      - kong-psql
    environment:
      - KONG_PG_HOST=${KONG_PG_HOST}
      - KONG_PG_USER=${KONG_PG_USER}
      - KONG_PG_DATABASE=${KONG_PG_DATABASE}
      - KONG_PG_PASSWORD=${KONG_PG_PASSWORD}
    command: kong migrations bootstrap
  kong-gateway:
    image: kong/kong-gateway:3.1.1.3-alpine
    restart: on-failure
    volumes:
      - ./bin/proxy-cache-graphql:/usr/local/bin/proxy-cache-graphql
      - ./logs:/home/kong/logs
    depends_on:
      - kong-psql
#      - kong-gateway-db-bootstrap
    environment:
      - KONG_REDIS_MASTER_HOST=${KONG_REDIS_MASTER_HOST}
      - KONG_REDIS_MASTER_PORT=${KONG_REDIS_MASTER_PORT}
      - KONG_REDIS_REPLICAS_HOST=${KONG_REDIS_REPLICAS_HOST}
      - KONG_REDIS_REPLICAS_PORT=${KONG_REDIS_REPLICAS_PORT}
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=${KONG_PG_HOST}
      - KONG_PG_USER=${KONG_PG_USER}
      - KONG_PG_DATABASE=${KONG_PG_DATABASE}
      - KONG_PG_PASSWORD=${KONG_PG_PASSWORD}
      - KONG_NGINX_MAIN_ENV=${KONG_NGINX_MAIN_ENV:-KONG_REDIS_MASTER_HOST; env KONG_REDIS_MASTER_PORT; env KONG_REDIS_REPLICAS_HOST; env KONG_REDIS_REPLICAS_PORT; env KONG_PG_HOST; env KONG_PG_USER; env KONG_PG_DATABASE; env KONG_PG_PASSWORD}
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_GUI_URL=${KONG_ADMIN_GUI_URL}
      - KONG_PLUGINS=proxy-cache-graphql, prometheus, rate-limiting
      - KONG_PLUGINSERVER_NAMES=proxy-cache-graphql
      - KONG_PLUGINSERVER_PROXY_CACHE_GRAPHQL_START_CMD=/usr/local/bin/proxy-cache-graphql
      - KONG_PLUGINSERVER_PROXY_CACHE_GRAPHQL_QUERY_CMD=/usr/local/bin/proxy-cache-graphql -dump
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"
  kong-promtail:
    image: grafana/promtail:main
    command: -config.file=/etc/promtail/promtail.yaml
    volumes:
      - ./config:/etc/promtail
      - ./logs:/var/log
  kong-prometheus:
    image: prom/prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  fiber-app:
    build: ./fiber-app/.
    volumes:
      - ./fiber-app:/fiber-app
    ports:
      - "9080:9080"
    environment:
      - KONG_REDIS_MASTER_HOST=${KONG_REDIS_MASTER_HOST}
      - KONG_REDIS_MASTER_PORT=${KONG_REDIS_MASTER_PORT}
  graphql-portal:
    build: ./graphql-portal/.
    volumes:
      - ./graphql-portal/:/app/
    ports:
      - "3001:3000"
  countries:
    build: ./countries/.
    volumes:
      - ./countries/:/app/
    ports:
      - "8787:8787"