version: "3.7"
services:
#  gin-app:
#    build: .
#    ports:
#      - "9080:8080"
  kong-redis:
    image: redis:latest
    volumes:
      - ./db/redis:/data
    ports:
      - "6379:6379"
  kong-database:
    image: postgres:9.6
    volumes:
      - ./db/psql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kongpass
    ports:
      - "5432:5432"
  kong-gateway:
    image: kong/kong-gateway:3.1.1.3-alpine
    restart: on-failure
    volumes:
      - ./bin/go-wait:/usr/local/bin/go-wait
      - ./bin/proxy-cache-graphql:/usr/local/bin/proxy-cache-graphql
      - ./kong/plugins/hello-world:/usr/local/share/lua/5.1/kong/plugins/hello-world
    depends_on:
      - kong-database
#    command: kong migrations bootstrap
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kongpass
#      - KONG_LOG_LEVEL=info
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_GUI_URL=http://localhost:8002
      - KONG_PLUGINS=proxy-cache-graphql, go-wait, hello-world
      - KONG_PLUGINSERVER_NAMES=proxy-cache-graphql, go-wait, num2word
      - KONG_PLUGINSERVER_GO_WAIT_QUERY_CMD=/usr/local/bin/go-wait -dump
      - KONG_PLUGINSERVER_PROXY_CACHE_GRAPHQL_QUERY_CMD=/usr/local/bin/proxy-cache-graphql -dump
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"
