version: "3.7"
services:
  kong-redis:
    image: redis:latest
    volumes:
      - ./db/redis:/data
    ports:
      - "6379:6379"
  kong-redis-replicas:
    image: redis:latest
    command: "redis-server --replicaof kong-redis 6379"
    ports:
      - "6380:6379"
    restart: on-failure
    depends_on:
      - kong-redis
  kong-psql:
    image: postgres:9.6
    volumes:
      - ./db/psql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kongpass
    ports:
      - "5432:5432"
#  kong-gateway-db-bootstrap:
#    image: kong/kong-gateway:3.1.1.3-alpine
#    restart: on-failure
#    depends_on:
#      - kong-psql
#    environment:
#      - KONG_DATABASE=postgres
#      - KONG_PG_HOST=kong-psql
#      - KONG_PG_USER=kong
#      - KONG_PG_PASSWORD=kongpass
#    command: kong migrations bootstrap
  kong-gateway:
    image: kong/kong-gateway:3.1.1.3-alpine
    restart: on-failure
    volumes:
      - ./bin/proxy-cache-graphql:/usr/local/bin/proxy-cache-graphql
      - ./kong/plugins/hello-world:/usr/local/share/lua/5.1/kong/plugins/hello-world
      - ./logs:/home/kong/logs
    depends_on:
      - kong-psql
#      - kong-gateway-db-bootstrap
    environment:
      - KONG_REDIS_MASTER_HOST=${KONG_REDIS_MASTER_HOST}
      - KONG_REDIS_MASTER_PORT=${KONG_REDIS_MASTER_PORT}
      - KONG_REDIS_REPLICAS_HOST=${KONG_REDIS_REPLICAS_HOST}
      - KONG_REDIS_REPLICAS_PORT=${KONG_REDIS_REPLICAS_PORT}
      - KONG_DATABASE=postgres
      - KONG_NGINX_MAIN_ENV=${KONG_NGINX_MAIN_ENV:-KONG_REDIS_MASTER_HOST; env KONG_REDIS_MASTER_PORT; env KONG_REDIS_REPLICAS_HOST; env KONG_REDIS_REPLICAS_PORT}
      - KONG_PG_HOST=kong-psql
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kongpass
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_GUI_URL=http://localhost:8002
      - KONG_PLUGINS=proxy-cache-graphql, hello-world, prometheus
      - KONG_PLUGINSERVER_NAMES=proxy-cache-graphql
      - KONG_PLUGINSERVER_PROXY_CACHE_GRAPHQL_START_CMD=/usr/local/bin/proxy-cache-graphql
      - KONG_PLUGINSERVER_PROXY_CACHE_GRAPHQL_QUERY_CMD=/usr/local/bin/proxy-cache-graphql -dump
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"
  fiber-app:
    build: ./fiber-app/.
    volumes:
      - ./fiber-app:/fiber-app
    ports:
      - "9080:9080"
    environment:
      - KONG_REDIS_MASTER_HOST=${KONG_REDIS_MASTER_HOST}
      - KONG_REDIS_MASTER_PORT=${KONG_REDIS_MASTER_PORT}