server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: https://359690:glc_eyJvIjoiNzczMjA3IiwibiI6ImtvbmdfcGx1Z2luX2xva2kiLCJrIjoiMHk1U2czUU5ZMkRrQTFxbTc3M0JUNEwwIiwibSI6eyJyIjoidXMifX0=@logs-prod-017.grafana.net/api/prom/push

scrape_configs:
  - job_name: system
    # transform log content
    pipeline_stages:
      - json:
          expressions:
            level: level
      - labels:
          level:
    # define log target
    static_configs:
      - targets:
          - localhost
        labels:
          job: proxy-cache
          __path__: /var/log/*.log